[module user admin]
[access feature=manage-[data.resource],get_[data.resource],(any)_[data.resource]]
[set page-title="[field-name [data.resource]]"]
[set html-classes="admin-page" append]
[admin-html]
