[module user admin forms]
[access feature=add_[data.resource],(any)_[data.resource]]
[set page-title="Add [resource-name [data.resource]]"]
[set bar-title="Admin | Add [resource-name [data.resource]]"]
[html]
