[module user admin forms]
[access feature=manage-[data.resource],add_[data.resource],(any)_[data.resource]]
[set page-title="Add [resource-name [data.resource]]"]
[set bar-title="Admin | Add [resource-name [data.resource]]"]
[set html-classes="admin-page" append]
[admin-html]
